I certify that this project is my own work and is not the work of others. I agree not to share my solution with others. - John Saia

# Linear equations with Scipy

## Solve for v, w, x, y, and z for the following system of equations.

 16v +17w +12x  +66y +45z = 156<br>
 29v -18w -15x  +73y +70z = 139<br>
-14v +46w -27x  +58y +91z = 154<br>
 33v +37w +24x -123y +54z =  25<br>
 20v -27w +18x  +19y -56z = -26<br>

### Import numpy and linalg from scipy

In [9]:
import numpy as np
from scipy import linalg

### Create numpy arrays representing the linear equations

In [10]:
eq_array = np.array([[16, 17, 12, 66, 45],
                     [29, -18, -15, 73, 70],
                     [-14, 46, -27, 58, 91],
                     [33, 37, 24, -123, 54],
                     [20, -27, 18, 19, -56]])

print(eq_array)

[[  16   17   12   66   45]
 [  29  -18  -15   73   70]
 [ -14   46  -27   58   91]
 [  33   37   24 -123   54]
 [  20  -27   18   19  -56]]


In [11]:
eq_ans = np.array([[156],
                   [139],
                   [154],
                   [25],
                   [-26]])
print(eq_ans)

[[156]
 [139]
 [154]
 [ 25]
 [-26]]


### Solve the equation with np.linalg.solve()

In [12]:
result = np.linalg.solve(eq_array,eq_ans)
print(result)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


### Confirm the solution by getting the product of eq_array matrix and solution matrix equaling eq_ans array

In [13]:
print(eq_array.dot(result))

[[156.]
 [139.]
 [154.]
 [ 25.]
 [-26.]]


### Solution

v = 1<br>
w = 1<br>
x = 1<br>
y = 1<br>
z = 1<br>